### ISSUE TITLE
Can't compile with -std=c++11 (version 2.2)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OlafvdSpek/ctemplate#103]
```
What steps will reproduce the problem?
1. Write a C++ file which include's <ctemplate/template.h>

e.g.:

#include <ctemplate/template.h>
int main() { return 0; }

2. Compile it using clang with -std=c++11, e.g.:

clang++ -std=c++11 --stdlib=c++ main.cpp -o main -lctemplate


What is the expected output? 

Successful compile


What do you see instead?

In file included from ctemplate-2.2/src/ctemplate/template_cache.h:43:
ctemplate-2.2/src/ctemplate/template_string.h:340:21: error: invalid suffix on 
literal; C++11 requires a space between literal and identifier 
[-Wreserved-user-defined-literal]
  { { str, sizeof(""str"")-1, hash } };                                       \


What version of the product are you using? On what operating system?

Using ctemplate 2.2, running on OS X 10.9.2 with Xcode 5.1 (clang-503.0.38 
based on LLVM 3.4svn) 

Please provide any additional information below.

The program compiles and runs cleanly with the latest version of trunk (r139). 
If you would package that up into version 2.3, that would resolve this issue.


```

Original issue reported on code.google.com by `lorin.ho...@sendgrid.com` on 19 Mar 2014 at 6:40
