### ISSUE TITLE
hash_compare missing in gcc version 4.2.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OlafvdSpek/ctemplate#25]
```
What steps will reproduce the problem?
1. run .configure to get config.h
2. add files to eclipse IDE project
3. compile on ubuntu 8.04 64 bit. gcc version 4.2.3 (Ubuntu 4.2.3-2ubuntu7) 

What is the expected output? What do you see instead?
  compile fails.

What version of the product are you using? On what operating system?
  ubuntu 8.04 64 bit. gcc version 4.2.3 (Ubuntu 4.2.3-2ubuntu7) 
  Using eclipse IDE.

Please provide any additional information below.

make all 
Building file: ../source/template.cc
Invoking: GCC C++ Compiler
g++ -I"/home/jay/axion/ctemplate/source"
-I"/home/jay/axion/ctemplate/source/base"
-I"/home/jay/axion/ctemplate/source/google" -O0 -g3 -Wall -c
-fmessage-length=0 -MMD -MP -MF"source/template.d" -MT"source/template.d"
-o"source/template.o" "../source/template.cc"
In file included from
/home/jay/axion/ctemplate/source/google/template_dictionary.h:57,
                 from /home/jay/axion/ctemplate/source/google/template.h:51,
                 from ../source/template.cc:58:
/home/jay/axion/ctemplate/source/google/template_modifiers.h:289: error:
‘hash_compare’ was not declared in this scope
/home/jay/axion/ctemplate/source/google/template_modifiers.h:289: error:
template argument 3 is invalid
/home/jay/axion/ctemplate/source/google/template_modifiers.h:289: error:
expected unqualified-id before ‘,’ token
/home/jay/axion/ctemplate/source/google/template_modifiers.h:292: error:
‘DataMap’ does not name a type
In file included from /home/jay/axion/ctemplate/source/google/template.h:51,
                 from ../source/template.cc:58:

as provided the source code references missing include files.
Changed includes to
#include <ext/hash_set>
#include <ext/hash_map>

this defines hash_map but neither defines the compare operator.



```

Original issue reported on code.google.com by `JSpren...@gmail.com` on 3 Nov 2008 at 5:04
