### ISSUE TITLE
Not sure if This is an Issue or just me.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OlafvdSpek/ctemplate#31]
```
I have code that worked fine with 0.92 and in 0.93 either refuses to
compile or if compiled refuses to run.

What steps will reproduce the problem?
1. Create main.cpp and add the following

#include <google/template_dictionary.h>
#include "template.h"

using google::Template;
using google::TemplateDictionary;

 TemplateDictionary * dict;
/*
 * 
 */
int main(int argc, char** argv)
{
    dict = new TemplateDictionary("class");

    return (EXIT_SUCCESS);
}

2. Try to compile with:
g++  -I/usr/local/include/google -lctemplate_nothreads main.cpp


What is the expected output? What do you see instead?

In 0.92 it would compile, instead with 0.93 I get the following:

/tmp/cc4izpr8.o: In function
`__static_initialization_and_destruction_0(int, int)':
main.cpp:(.text+0x28): undefined reference to
`google::StaticTemplateStringInitializer::StaticTemplateStringInitializer(google
::StaticTemplateString
const*)'
collect2: ld returned 1 exit status

With some fiddling I can get it to compile however when it does it produces
the following runtime error:

 symbol lookup error: ./dist/Debug/test: undefined symbol:
_ZN6google31StaticTemplateStringInitializerC1EPKNS_20StaticTemplateStringE

What version of the product are you using? On what operating system?
0.93 Linux - SuSe 11.1 64 bit

```

Original issue reported on code.google.com by `silenuzn...@yahoo.com` on 7 Feb 2009 at 5:32
